<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Apply extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
		$this->load->view('apply', array('error' => ' ' ));
    } 

    public function aksi_upload(){
		$config['upload_path']          = './berkas/';
		$config['allowed_types']        = 'gif|jpg|png';
		$config['max_size']             = 1000;
		$config['max_width']            = 10240;
		$config['max_height']           = 7680;
 
		$this->load->library('upload', $config);
 
		if (!$this->upload->do_upload('cv')){
			$error = array('error' => $this->upload->display_errors());
			$this->load->view('apply', $error);
		}else{
			$data = array('upload_data' => $this->upload->data());
			$this->load->view('v_upload_sukses', $data);
		}
	}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */